[http]
  [http.routers]
    [http.routers.http-catchall]
      rule = "HostRegexp(`{host:.+}`)"
      entryPoints = ["web"]
      middlewares = ["https-redirect"]

  [http.middlewares]
    [http.middlewares.https-redirect.redirectScheme]
      scheme = "https"

  [http.services]
    [http.services.dummy-service.loadBalancer]
      [[http.services.dummy-service.loadBalancer.servers]]
        url = "http://127.0.0.1"

[tls]
  [tls.certificates]
    [tls.certificates.default]
      certFile = "/path/to/local/cert.crt"
      keyFile = "/path/to/local/key.key"

  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"

[certificatesResolvers]
  [certificatesResolvers.letsencrypt.acme]
    email = "your-email@example.com"
    storage = "/etc/traefik/acme.json"
    [certificatesResolvers.letsencrypt.acme.tlsChallenge]
